# Generated by Django 3.2.15 on 2022-09-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='imagenes2')),
                ('nombre', models.CharField(max_length=250)),
                ('sobre', models.TextField()),
            ],
        ),
    ]
